import { Button, Chip, FooterColumns, RecommendationCard } from "@/components/ui";
import { getIssues } from "@/lib/content";

export default function HomePage() {
  const issues = getIssues();
  const latest = issues[0];

  return (
    <main className="mx-auto w-full max-w-6xl px-6 pb-16 pt-10">
      <section className="rounded-2xl border border-border bg-bgMuted/50 p-8">
        <p className="mb-3 text-xs uppercase tracking-[0.16em] text-fgMuted">Daily editorial signal</p>
        <h1 className="max-w-3xl text-4xl font-semibold tracking-tight">AI research briefing designed for fast scan and deep follow-up.</h1>
        <p className="mt-4 max-w-2xl text-base text-fgMuted">
          This v2 frontend is generated by the Codex design workflow and fed by OpenClaw-organized issue data.
        </p>
        <div className="mt-6 flex flex-wrap items-center gap-3">
          <Button href={latest ? `/issues/${latest.date}/${latest.papers[0]?.id ?? ""}` : "/"}>Open latest article</Button>
          <Button href="https://huggingface.co/papers" variant="secondary">Browse source feed</Button>
          <Chip>System font stack</Chip>
          <Chip>Accessible by default</Chip>
          <Chip>No heavy UI libs</Chip>
        </div>
      </section>

      <section className="mt-14">
        <h2 className="mb-5 text-2xl font-semibold">Issue archive</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {issues.flatMap((issue) =>
            issue.papers.slice(0, 2).map((paper) => (
              <RecommendationCard
                key={`${issue.date}-${paper.id}`}
                title={paper.title}
                summary={paper.summary}
                date={issue.date}
                href={`/issues/${issue.date}/${paper.id}`}
              />
            ))
          )}
        </div>
      </section>

      <FooterColumns />
    </main>
  );
}
